// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package customTypes

type User struct {
	ID        int     `json:"id" gorm:"primaryKey" `
	Email     string  `json:"email"`
	UID       string  `json:"uid"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
	DeletedAt *string `json:"deleted_at,omitempty"`
}
