version: "3.1"

services:
  # shipeasecommerce:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - "postgres"
  #   volumes:
  #     - .:/go/src/github.com/ronnycoding/shipeasecommerce
  #   # platform: linux/amd64 # Don't know if this is needed
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - $PWD/config/postgresql.conf:/etc/postgresql/postgresql.conf
      - psqldata:/var/lib/postgresql/data
      # - $PWD/migration/20221013210124_add_user_table.sql:/docker-entrypoint-initdb.d/20221013210124_add_user_table.sql
      # - $PWD/migration/20221013210529_add_role_table.sql:/docker-entrypoint-initdb.d/20221013210529_add_role_table.sql
      # - $PWD/migration/20221013212646_add_user_role_table.sql:/docker-entrypoint-initdb.d/20221013212646_add_user_role_table.sql
      # - $PWD/migration/20221112150823_add_brand_table.sql:/docker-entrypoint-initdb.d/20221112150823_add_brand_table.sql
      # - $PWD/migration/20221112150831_add_model_table.sql:/docker-entrypoint-initdb.d/20221112150831_add_model_table.sql
      # - $PWD/migration/20221112170819_add_post_table.sql:/docker-entrypoint-initdb.d/20221112170819_add_post_table.sql
      # - $PWD/migration/20221205123710_add_user_post_table.sql:/docker-entrypoint-initdb.d/20221112170819_add_post_table.sql
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped

volumes:
  psqldata: {}
